name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * 1-5

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Nodejs and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22

      - name: Install Newman and Htmlextra
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra
